config/routes.rb
SocialClue::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  mount StripeEvent::Engine => '/stripe-webhooks'

  match 'auth/facebook/callback', to: 'sessions#create_facebook', via: [:get, :post]
  get '/auth/twitter/callback', to: 'sessions#create_twitter'

  delete '/appauth/signout', to: 'sessions#destroy'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :home, :only => [:index]

  get '/dashboard', to: 'dashboard#index'

  resources :subscriptions, only: [:new, :create] do
    put 'cancel', on: :collection
  end
  match 'subscriptions/edit',   to: 'subscriptions#edit',   via: 'get'
  match 'subscriptions/update', to: 'subscriptions#update', via: 'put'

  resources :pages, :only => [:about, :faq] do
    collection do
      get 'about'
      get 'learn_more'
      get 'privacy_policy'
      get 'terms_of_service'
      get 'pricing'
    end
  end

  namespace :twitter do
    resources :analytics, :only => [:start, :sentiment, :stats, :keywords] do
      collection do
        get 'start'
        get 'sentiment'
        get 'stats'
        get 'keywords'
      end
    end
    resources :photos, :only => [:search] do
      get 'search', on: :collection
    end
    resources :info, :only => [:about] do
      get 'about', on: :collection
    end
    resources :geo_search, :only => [:sentiment, :stats, :keywords, :search] do
      collection do
        get 'sentiment'
        get 'stats'
        get 'keywords'
        get 'search'
      end
    end
  end

  namespace :facebook do
    resources :analytics, :only => [:start, :search, :feed, :stats, :keywords] do
      collection do
        get 'start'
        get 'search'
        get 'feed'
        get 'stats'
        get 'keywords'
      end
    end
  end

  resources :invoices, only: [:index, :show]

  resources :accounts, only: [:show]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  root :to => 'home#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  before_filter :authenticate_active_user

  def index
  end

end

app/views/dashboard/_admin_layout_sidebar_dashboard.html.haml
%li
  %a{href: "#"}
    Twitter
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      = link_to start_twitter_analytics_path do
        Search

%li
  %a{href: "#"}
    Facebook
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      = link_to start_facebook_analytics_path do
        Search

app/views/dashboard/index.html.haml
- if user_signed_in?
  = stylesheet_link_tag "timeline", media: "all"
  = stylesheet_link_tag "sb-admin", media: "all"
  = render "shared/admin_layout"
  .navbar-default.navbar-static-side{role: "navigation"}
    .sidebar-collapse
      %ul#side-menu.nav
        = render "dashboard/admin_layout_sidebar_dashboard"
  #page-wrapper
    .row
      .col-lg-12
        %h1.page-header Select a network
    .row
      .col-lg-6
        %a{style: "text-decoration: none", href: "/twitter/analytics/start"}
          .well.well-lg.twitter{"style" => "min-height: 275px; overflow: hidden"}
            %ul
              %h2 Twitter
            %hr
            .row{style: "font-size: 18px"}
              .col-sm-6
                %ul
                  %p Search
                  %p Sentiment
              .col-sm-6
                %ul
                  %p Metrics
                  %p Keywords
            %br
            .row{style: "font-size: 18px"}
              .col-sm-6
                %ul
                  %button.btn.btn-primary#auth-twitter Get started
              .col-sm-6
            .row
              .col-sm-12
                %hr
                  %ul
                    %small *You will need your twitter account to use this service
      .col-lg-6
        %a{style: "text-decoration: none", href: "/facebook/analytics/start"}
          .well.well-lg.facebook{"style" => "min-height: 275px; overflow: hidden"}
            %ul
              %h2 Facebook
            %hr
            .row{style: "font-size: 18px"}
              .col-sm-6
                %ul
                  %p Search
                  %p Sentiment
              .col-sm-6
                %ul
                  %p Metrics
                  %p Keywords
            %br
            .row{style: "font-size: 18px"}
              .col-sm-6
                %ul
                  %button.btn.btn-primary#auth-facebook Get started
              .col-sm-6
            .row
              .col-sm-12
                %hr
                  %ul
                    %small *You will need your facebook account to use this service
- else
  #flash_notice
    %h3 Are you lost? Please sign in first and try again.