config/routes.rb
SocialClue::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  mount StripeEvent::Engine => '/stripe-webhooks'

  match 'auth/facebook/callback', to: 'sessions#create_facebook', via: [:get, :post]
  get '/auth/twitter/callback', to: 'sessions#create_twitter'

  delete '/appauth/signout', to: 'sessions#destroy'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :home, :only => [:index]

  get '/dashboard', to: 'dashboard#index'

  resources :subscriptions, only: [:new, :create] do
    put 'cancel', on: :collection
  end
  match 'subscriptions/edit',   to: 'subscriptions#edit',   via: 'get'
  match 'subscriptions/update', to: 'subscriptions#update', via: 'put'

  resources :pages, :only => [:about, :faq] do
    collection do
      get 'about'
      get 'learn_more'
      get 'privacy_policy'
      get 'terms_of_service'
      get 'pricing'
    end
  end

  namespace :twitter do
    resources :analytics, :only => [:start, :sentiment, :stats, :keywords] do
      collection do
        get 'start'
        get 'sentiment'
        get 'stats'
        get 'keywords'
      end
    end
    resources :photos, :only => [:search] do
      get 'search', on: :collection
    end
    resources :info, :only => [:about] do
      get 'about', on: :collection
    end
    resources :geo_search, :only => [:sentiment, :stats, :keywords, :search] do
      collection do
        get 'sentiment'
        get 'stats'
        get 'keywords'
        get 'search'
      end
    end
  end

  namespace :facebook do
    resources :analytics, :only => [:start, :search, :feed, :stats, :keywords] do
      collection do
        get 'start'
        get 'search'
        get 'feed'
        get 'stats'
        get 'keywords'
      end
    end
  end

  resources :invoices, only: [:index, :show]

  resources :accounts, only: [:show]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  root :to => 'home#index'

end

app/views/shared/_admin_layout.html.haml
= stylesheet_link_tag "sb-admin", media: "all"
#wrapper
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation", style: "margin-bottom: 0"}
    .navbar-header
      %button.navbar-toggle{"data-target" => ".sidebar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to 'SocialClue', dashboard_path
    %ul.nav.navbar-top-links.navbar-right
      - if user_signed_in?
        %li
          = link_to account_path(current_user) do
            %i.fa.fa-user.fa-fw#user-account
            Account
        %li
          = link_to destroy_user_session_path,:method => :delete do
            %i.fa.fa-sign-out.fa-fw
            Sign out
      - else
        %li= link_to 'Sign in', new_user_session_path
        %li= link_to 'Sign up', new_user_registration_path
  = render partial: "shared/flash_messages", flash: flash

app/views/shared/_flash_messages.html.haml
- devise_flash
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} fade in"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/shared/_landing_page_footer.html.haml
.container.footer-custom.text-center
  .row.break-top
    .col-lg-6.col-lg-offset-3
      %ul
        %li#about
          = link_to about_pages_path do
            %h4 About -
        %li#learn-more
          = link_to learn_more_pages_path do
            %h4 Learn More -
        %li
          %a{href: "mailto:info@socialclue.io"}
            %h4 Contact Us
  .row.break-bottom
    .col-lg-6.col-lg-offset-3
      %ul
        %li
          %h5 &#169; 2014 SocialClue Ltd. All rights reserved.
        %li#privacy-policy
          = link_to privacy_policy_pages_path do
            %h5 Privacy Policy.
        %li#terms-of-service
          = link_to terms_of_service_pages_path do
            %h5 Terms of Service.

app/views/shared/_landing_page_header.html.haml
= stylesheet_link_tag "flatty", media: "all"
%nav.navbar.navbar-default.navbar-logo-rf
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand#header-logo
        = link_to "SocialClue.io", root_path
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right.navbar-header-links
        %l
        - if user_signed_in?
          %li#dashboard= link_to 'Dashboard', dashboard_path
          %li#user-account= link_to 'Account', account_path(current_user)
          %li= link_to 'Sign out', destroy_user_session_path, :method => :delete
          - if current_user.is_admin?
            %li= link_to 'Admin', admin_dashboard_path
        - else
          %li#pricing= link_to 'Pricing', pricing_pages_path
          %li= link_to 'Sign in', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path
  = render partial: "shared/flash_messages", flash: flash