config/routes.rb
SocialClue::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  mount StripeEvent::Engine => '/stripe-webhooks'

  match 'auth/facebook/callback', to: 'sessions#create_facebook', via: [:get, :post]
  get '/auth/twitter/callback', to: 'sessions#create_twitter'

  delete '/appauth/signout', to: 'sessions#destroy'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :home, :only => [:index]

  get '/dashboard', to: 'dashboard#index'

  resources :subscriptions, only: [:new, :create] do
    put 'cancel', on: :collection
  end
  match 'subscriptions/edit',   to: 'subscriptions#edit',   via: 'get'
  match 'subscriptions/update', to: 'subscriptions#update', via: 'put'

  resources :pages, :only => [:about, :faq] do
    collection do
      get 'about'
      get 'learn_more'
      get 'privacy_policy'
      get 'terms_of_service'
      get 'pricing'
    end
  end

  namespace :twitter do
    resources :analytics, :only => [:start, :sentiment, :stats, :keywords] do
      collection do
        get 'start'
        get 'sentiment'
        get 'stats'
        get 'keywords'
      end
    end
    resources :photos, :only => [:search] do
      get 'search', on: :collection
    end
    resources :info, :only => [:about] do
      get 'about', on: :collection
    end
    resources :geo_search, :only => [:sentiment, :stats, :keywords, :search] do
      collection do
        get 'sentiment'
        get 'stats'
        get 'keywords'
        get 'search'
      end
    end
  end

  namespace :facebook do
    resources :analytics, :only => [:start, :search, :feed, :stats, :keywords] do
      collection do
        get 'start'
        get 'search'
        get 'feed'
        get 'stats'
        get 'keywords'
      end
    end
  end

  resources :invoices, only: [:index, :show]

  resources :accounts, only: [:show]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  root :to => 'home#index'

end

app/models/facebook/application_frequency.rb
class Facebook::ApplicationFrequency

  include DataFrequency

  def initialize graph_feed_data
    filter_feed_data graph_feed_data
    calculate_frequency
  end

  private

  def filter_feed_data data
    data.each do |feed_object|
      next unless feed_object[:application]
        raw_data << feed_object[:application]
    end
  end
end

app/models/facebook/most_shared.rb
class Facebook::MostShared

  def initialize nodes
    @sentiment_analysis = Facebook::SentimentAnalysis.new(nodes).message_sentiment
  end

  def top_results
    filter_feed_data.sort_by &:first
  end

  private

  def filter_feed_data
    @sentiment_analysis.each_with_object({}) do |(k, v), most_shared|
      next unless k[:shares].to_i > 0
        most_shared[k[:shares]] = k
    end
  end
end

app/models/facebook/status_type_frequency.rb
class Facebook::StatusTypeFrequency

  include DataFrequency

  def initialize graph_feed_data
    filter_feed_data graph_feed_data
    calculate_frequency
  end

  private

  def filter_feed_data data
    data.each do |feed_object|
      next unless feed_object[:status_type]
        raw_data << feed_object[:status_type]
    end
  end
end

app/models/facebook/type_frequency.rb
class Facebook::TypeFrequency

  include DataFrequency

  def initialize graph_feed_data
    filter_feed_data graph_feed_data
    calculate_frequency
  end

  private

  def filter_feed_data data
    data.each do |feed_object|
      next unless feed_object[:type]
        raw_data << feed_object[:type]
    end
  end

end

app/controllers/facebook/analytics_controller.rb
class Facebook::AnalyticsController < Facebook::FacebookController

  before_filter :auth_facebook_account
  before_filter :initialize_graph_api

  def start
  end

  def search
    @graph_data = Facebook::SearchPresenter.new(graph_search_results).present_nodes
    fb_search_params
  end

  def feed
    @graph_feed = Facebook::FeedPresenter.new(graph_feed_connections)
  end

  def stats
    @fb_stats = Facebook::StatsPresenter.new(graph_feed_connections)
  end

  def keywords
    @fb_keywords = Facebook::KeywordsPresenter.new(graph_feed_connections)
  end

  private

  def fb_search_params
    session[:fb_search_query] = nil
    session[:fb_search_type] = nil
    session[:fb_search_query] = params[:q]
    session[:fb_search_type] = params[:type]
  end

  def graph
    initialize_graph_api
  end

  def auth_facebook_account
    redirect_to "/auth/facebook" unless current_facebook_account
  end

  def graph_search_results
    graph.search(params[:q], {type: params[:type]})
  end

  def graph_feed_connections
    if params[:type] == 'page'
      graph.get_connections(params[:id], "posts")
    else
      graph.get_connections(params[:id], "feed")
    end
  end

end

app/controllers/facebook/facebook_controller.rb
class Facebook::FacebookController < ApplicationController

  before_filter :authenticate_user!
  before_filter :authenticate_active_user
  helper_method :current_facebook_account

  def initialize_graph_api
    Koala::Facebook::API.new(oauth_token)
  end

  def oauth_token
    current_facebook_account.oauth_token
  end

end

app/views/facebook/shared/_admin_layout_sidebar_analytics.html.haml
%li
  %a{href: "#"}
    / %i.fa.fa-facebook.fa-fw
    Facebook
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      = link_to start_facebook_analytics_path do
        Search
    %li
      %a{href: "#"}
        %i.fa.fa-bar-chart-o.fa-fw
        Analytics
        %span.fa.arrow
      %ul.nav.nav-third-level
        %li#fb-pages
          = link_to search_page_facebook_analytics_path(q: params[:q]) do
            Pages
        %li#fb-events
          = link_to search_event_facebook_analytics_path(q: params[:q]) do
            Events

app/views/facebook/shared/_admin_layout_sidebar_search.html.haml
%li
  %a{href: "#"}
    / %i.fa.fa-facebook.fa-fw
    Facebook
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      = link_to search_facebook_analytics_path(q: params[:q], type: 'page') do
        %i.fa.fa-rss#fb-pages
        Pages
    %li
      = link_to search_facebook_analytics_path(q: params[:q], type: 'event') do
        %i.fa.fa-calendar#fb-events
        Events
    %li
      = link_to start_facebook_analytics_path do
        %i.fa.fa-search-plus
        New Search

app/views/facebook/shared/_admin_layout_sidebar_start.html.haml
%li
  %a{href: "#"}
    / %i.fa.fa-facebook.fa-fw
    Facebook
    %span.fa.arrow
  %ul.nav.nav-second-level
    %li
      = link_to start_facebook_analytics_path do
        Search