config/routes.rb
SocialClue::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  mount StripeEvent::Engine => '/stripe-webhooks'

  match 'auth/facebook/callback', to: 'sessions#create_facebook', via: [:get, :post]
  get '/auth/twitter/callback', to: 'sessions#create_twitter'

  delete '/appauth/signout', to: 'sessions#destroy'
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :home, :only => [:index]

  get '/dashboard', to: 'dashboard#index'

  resources :subscriptions, only: [:new, :create] do
    put 'cancel', on: :collection
  end
  match 'subscriptions/edit',   to: 'subscriptions#edit',   via: 'get'
  match 'subscriptions/update', to: 'subscriptions#update', via: 'put'

  resources :pages, :only => [:about, :faq] do
    collection do
      get 'about'
      get 'learn_more'
      get 'privacy_policy'
      get 'terms_of_service'
      get 'pricing'
    end
  end

  namespace :twitter do
    resources :analytics, :only => [:start, :sentiment, :stats, :keywords] do
      collection do
        get 'start'
        get 'sentiment'
        get 'stats'
        get 'keywords'
      end
    end
    resources :photos, :only => [:search] do
      get 'search', on: :collection
    end
    resources :info, :only => [:about] do
      get 'about', on: :collection
    end
    resources :geo_search, :only => [:sentiment, :stats, :keywords, :search] do
      collection do
        get 'sentiment'
        get 'stats'
        get 'keywords'
        get 'search'
      end
    end
  end

  namespace :facebook do
    resources :analytics, :only => [:start, :search, :feed, :stats, :keywords] do
      collection do
        get 'start'
        get 'search'
        get 'feed'
        get 'stats'
        get 'keywords'
      end
    end
  end

  resources :invoices, only: [:index, :show]

  resources :accounts, only: [:show]

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#server_error'

  root :to => 'home#index'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :authenticate_user!, :only => [:show]

  def show
  end
end

app/views/accounts/show.html.haml
= render partial: "shared/landing_page_header"
#page-wrapper.text-center
  .row
    .col-md-4.col-sm-6.col-md-offset-4.col-sm-offset-3
      .panel.panel-primary.mobile-margin
        .panel-heading
          %h3.panel-title
            %strong#user-account
              My Account
        .panel-body
          %fieldset
            .form-group
              %h3.panel-title
                %strong
                  Profile
              %br
                .btn.btn-primary.account-edit-btn= link_to "Update Profile", edit_user_registration_path, method: :get
              %hr
            - if current_user.active_paying_subscription?
              .form-group
                %h3.panel-title
                  %strong
                    Update card details
                %br
                .btn.btn-primary.account-edit-btn= link_to "Edit card details", subscriptions_edit_path, method: :get
              %hr
              .form-group
                %h3.panel-title
                  %strong
                    Cancel my subscription
                %br
                .btn.btn-danger.account-edit-btn= link_to "Cancel subscription", cancel_subscriptions_path, method: :put
              %hr
            - if current_user.invoices.size > 0
              .form-group
                %h3.panel-title
                  %strong
                    Invoices
                %br
                .btn.btn-primary.account-edit-btn= link_to "View invoices", invoices_path, method: :get
= render "shared/landing_page_footer"